### ISSUE TITLE
随手刷到的,给点建议

### ISSUE THREAD

**Issue by qianbilili** [chenglulua/YouCha#1]
都用Spring了可以去整合mybatis,使用maven项目也不用自己手动导jar包了,学习成本也低,日后开发难度更加容易. 现在可以先集中讨论出涉及到的业务需求,再分配工作进行开发

**Comment by chenglulua** [comment]
> 都用Spring可以去整合mybatis，使用maven项目也不用自己手动引导jar包了，学习成本也低，日后开发难度更加容易。现在可以先集中讨论出涉及到的业务需求，再分配工作进行开发

刚刚才看到，非常感谢您的建议，谢谢。
